---
- name: Playbook for target_node 
  hosts: target_node
  become: yes
  roles:
    - { role: common, tags: common }       
    - { role: git, tags: git }
    - { role: mysql, tags: mysql }
    - { role: nginx, tags: nginx }
    - { role: nodejs, tags: nodejs }
    - { role: ruby, tags: ruby }  
